#!/bin/bash
# Source: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
set -e # Exit with nonzero exit code if anything fails

SOURCE_BRANCH="master"
TARGET_BRANCH="gh-pages"

function generate-docs {
    npm run storybook-build -s
}

# Pull requests shouldn't deploy
if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    echo "Pull request, skipping deploy"
    exit 0
fi
# Other branches shouldn't deploy
if [ "$TRAVIS_BRANCH" != "$SOURCE_BRANCH" ]; then
    echo "Branch $TRAVIS_BRANCH ignored, skipping build"
    exit 0
fi

# Save some useful information
REPO=`git config remote.origin.url`
SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
SHA=`git rev-parse --verify HEAD`

# Clone the existing gh-pages for this repo into gh-pages/
# Create a new empty branch if gh-pages doesn't exist yet (should only happen on first deply)
git clone $REPO gh-pages
cd gh-pages
git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
cd ..

# Run our compile script
generate-docs
# Copy to pages-repo
rm -rf gh-pages/$TRAVIS_BRANCH/storybook/*
cp -R docs/* gh-pages/$TRAVIS_BRANCH/storybook
# If building a tag, copy to new folder in pages
if [[ $TRAVIS_TAG ]]; then
    mkdir "gh-pages/$TRAVIS_TAG/storybook/"
    cp -R docs/* "gh-pages/$TRAVIS_TAG/storybook"
    echo "$TRAVIS_TAG\n" >> gh-pages/versions.txt
fi

cd gh-pages
git config user.name "Deployment Bot"
git config user.email "deploy@travis-ci.org"

# If there are no changes to the compiled docs then just bail.
if [ $(git status --porcelain | wc -l) -lt 1 ]; then
    echo "No changes to the output"
    exit 0
fi

# Commit the "changes", i.e. the new version.
# The delta will show diffs between new and old versions.
git add -A .
git commit -m "Deploy to GitHub Pages: ${SHA}"

# Add SSH-key for deployment
eval `ssh-agent -s`
# ssh-add will fail if broad permissions are given
chmod 600 ../deploy-key
ssh-add ../deploy-key

# Now that we're all set up, we can push.
git push $SSH_REPO $TARGET_BRANCH
